steps:
  # Step 1: Initialize Terraform
  - name: hashicorp/terraform:1.6.6
    id: terraform-init
    dir: Infra
    entrypoint: sh
    args:
      - -c
      - |
        terraform init \
          -backend-config="bucket=${_TF_STATE_BUCKET}" \
          -backend-config="prefix=${_TF_STATE_PREFIX}"

  # Step 2: Apply Artifact Registry first
  - name: hashicorp/terraform:1.6.6
    id: terraform-apply-ar-repo
    dir: Infra
    entrypoint: sh
    args:
      - -c
      - |
        echo "Apply AR repo"
        terraform apply -auto-approve \
          -var="project_id=${PROJECT_ID}" \
          -var="github_owner=${_GITHUB_OWNER}" \
          -var="github_repo_name=${_GITHUB_REPO}" \
          -target=google_artifact_registry_repository.dbt_images

  # Step 3: Configure Docker for Artifact Registry
  - name: gcr.io/cloud-builders/gcloud
    id: configure-docker
    args:
      - auth
      - configure-docker
      - "${_AR_REGION}-docker.pkg.dev"
      - --quiet

  # Step 4: Build and push custom dbt image
  - name: gcr.io/cloud-builders/docker
    id: build-dbt-job-image
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        DEST_IMAGE="${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_DBT_JOB_IMAGE_NAME}:${_DBT_JOB_IMAGE_TAG}"
        docker build -f dbt-code/Dockerfile -t "$$DEST_IMAGE" dbt-code
        docker push "$$DEST_IMAGE"

  # Step 5: Terraform plan with custom image
  - name: hashicorp/terraform:1.6.6
    id: terraform-plan
    dir: Infra
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan \
          -var="project_id=${PROJECT_ID}" \
          -var="region=${_AR_REGION}" \
          -var="github_owner=${_GITHUB_OWNER}" \
          -var="github_repo_name=${_GITHUB_REPO}" \
          -var="dbt_image=${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_DBT_JOB_IMAGE_NAME}:${_DBT_JOB_IMAGE_TAG}" \
          -out=tfplan

  # Step 6: Terraform apply
  - name: hashicorp/terraform:1.6.6
    id: terraform-apply
    dir: Infra
    entrypoint: sh
    args:
      - -c
      - |
        echo "Terraform apply"
        terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY