name: 'dbtetl'
version: '1.0.0'
config-version: 2

profile: 'dbtetl'

model-paths: ["models"]
target-path: "target"

models:
  dbtetl:
    staging:
      +materialized: view
    transform:
      +materialized: table