name:'dbtetl'
version:'1.0.0'
config-version:2

profile:'dbtetl'

model-paths:["models"]
target-path:"target"

models:
  dbtetl:          # 2 espaces ici
    staging:       # 4 espaces ici
      +materialized: view
    transform:     # 4 espaces ici
      +materialized: table