dbtetl:outputs:
    dev:
      # Method 1: Service Account (Production - Cloud Run)
      dataset: omza_dsy
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: service-account
      keyfile: /secrets/dbt-keyfile
      priority: interactive
      project: omza-2026-formation
      threads: 1
      type: bigquery