main:
  steps:
    - init:
        assign:
          - raw_bq_create_disposition: "CREATE_NEVER"
          - raw_bq_write_disposition: "WRITE_TRUNCATE"
          - dataset: "omza_dsy"
          - project_id: "omza-2026-formation"
          - region: "europe-west1"
          - dbt_job_name: "omza-etl-dbt-job"
          - raw_files_source_uri: "gs://omza-etl-dsy/dataset/"

    - load-countries-to-bigquery :
        call: googleapis.bigquery.v2.jobs.insert
        args:
          projectId: "omza-2026-formation"
          body:
            configuration:
              load:
                sourceUris: "gs://omza-etl-dsy/dataset/countries.csv"
                destinationTable:
                  projectId: "omza-2026-formation"
                  datasetId: "omza_dsy"
                  tableId: "raw_country"
                skipLeadingRows: 1
                schema:
                  fields:
                    - name: "id"
                      type: "STRING"
                    - name: "iso"
                      type: "STRING"
                    - name: "name"
                      type: "STRING"
                    - name: "nicename"
                      type: "STRING"
                    - name: "iso3"
                      type: "STRING"
                    - name: "numcode"
                      type: "STRING"
                    - name: "phonecode"
                      type: "STRING"
                createDisposition: "CREATE_NEVER"
                writeDisposition: "WRITE_TRUNCATE"
        result: loadCountryRawToBqResult

    - load-invoices-to-bigquery :
        call: googleapis.bigquery.v2.jobs.insert
        args:
          projectId: "omza-2026-formation"
          body:
            configuration:
              load:
                sourceUris: "gs://omza-etl-dsy/dataset/invoices.csv"
                destinationTable:
                  projectId: "omza-2026-formation"
                  datasetId: "omza_dsy"
                  tableId: "raw_invoice"
                skipLeadingRows: 1
                schema:
                  fields:
                    - name: "InvoiceNo"
                      type: "STRING"
                    - name: "StockCode"
                      type: "STRING"
                    - name: "Description"
                      type: "STRING"
                    - name: "Quantity"
                      type: "STRING"
                    - name: "InvoiceDate"
                      type: "STRING"
                    - name: "UnitPrice"
                      type: "STRING"
                    - name: "CustomerID"
                      type: "STRING"
                    - name: "Country"
                      type: "STRING"
                createDisposition: "CREATE_NEVER"
                writeDisposition: "WRITE_TRUNCATE"
        result: loadInvoiceRawToBqResult
    # execute Cloud Run job to trigger dbt
    - trigger-dbt-job:
        call: http.post
        args:
          url: ${"https://run.googleapis.com/v2/projects/" + project_id + "/locations/" + region + "/jobs/" + dbt_job_name + ":run"}
          auth:
            type: OAuth2
        result: dbtJobResult

    - returnResult:
        return: ${dbtJobResult}
